language: node_js
node_js:
  - "7"
install:
  - "npm install && bower install && mkdir build"
script:
  - "./scripts/deploy-demo src/gan-playground.ts src/gan-playground-index.html build"
  - "mv build/gan-playground-index.html build/index.html"
  - "cp src/support.js build/support.js"
  - "cp src/*.json build/"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: "build"
